@startuml
@startuml

class de.dblab.domain.Angestellte
class de.dblab.domain.Schaechte
class de.dblab.domain.Zeit
class de.dblab.page.DataBaseService
class de.dblab.page.HomePage
class de.dblab.page.TemplatePage
class de.dblab.page.angestellte.AngestellteEditPage
class de.dblab.page.angestellte.AngestellteNewForm
class de.dblab.page.angestellte.AngestelltePage
class de.dblab.page.angestellte.AngestellteSearchForm
class de.dblab.page.angestellte.AngestelterForm
class de.dblab.page.angestellte.NewClass
class de.dblab.page.angestellte.NewFormAngestellte
class de.dblab.page.schaechte.NewFormSchaechte
class de.dblab.page.schaechte.SchaechteEditPage
class de.dblab.page.schaechte.SchaechteForm
class de.dblab.page.schaechte.SchaechteNewForm
class de.dblab.page.schaechte.SchaechtePage
class de.dblab.page.schaechte.SchaechteSearchForm
class de.dblab.service.cayenne.Property


de.dblab.domain.Angestellte ..> java.lang.SuppressWarnings
de.dblab.domain.Angestellte ..> de.dblab.service.cayenne.Property
de.dblab.domain.Angestellte ..> java.util.Date
de.dblab.domain.Angestellte ..> java.util.HashMap
de.dblab.domain.Angestellte ..> java.util.List
de.dblab.domain.Angestellte --|> org.apache.cayenne.CayenneDataObject
de.dblab.domain.Angestellte ..> org.apache.cayenne.exp.Expression
de.dblab.domain.Schaechte ..> java.lang.SuppressWarnings
de.dblab.domain.Schaechte ..> de.dblab.service.cayenne.Property
de.dblab.domain.Schaechte ..> java.util.HashMap
de.dblab.domain.Schaechte ..> java.util.List
de.dblab.domain.Schaechte --|> org.apache.cayenne.CayenneDataObject
de.dblab.domain.Schaechte ..> org.apache.cayenne.exp.Expression
de.dblab.domain.Zeit ..> java.text.SimpleDateFormat
de.dblab.domain.Zeit ..> java.util.Calendar
de.dblab.domain.Zeit ..> java.util.Date
de.dblab.domain.Zeit --|> org.apache.cayenne.CayenneDataObject
de.dblab.domain.Zeit ..> org.apache.cayenne.exp.Property
de.dblab.page.DataBaseService ..> de.dblab.domain.Angestellte
de.dblab.page.DataBaseService ..> de.dblab.domain.Schaechte
de.dblab.page.DataBaseService ..> de.dblab.domain.Zeit
de.dblab.page.DataBaseService ..> java.util.ArrayList
de.dblab.page.DataBaseService ..> java.util.Date
de.dblab.page.DataBaseService ..> java.util.HashMap
de.dblab.page.DataBaseService ..> java.util.List
de.dblab.page.DataBaseService ..> org.apache.cayenne.BaseContext
de.dblab.page.DataBaseService ..> org.apache.cayenne.CayenneDataObject
de.dblab.page.DataBaseService ..> org.apache.cayenne.ObjectContext
de.dblab.page.DataBaseService ..> org.apache.cayenne.configuration.server.ServerRuntime
de.dblab.page.DataBaseService ..> org.apache.cayenne.exp.Expression
de.dblab.page.DataBaseService ..> org.apache.cayenne.exp.ExpressionFactory
de.dblab.page.DataBaseService ..> org.apache.cayenne.query.SQLTemplate
de.dblab.page.DataBaseService ..> org.apache.cayenne.query.SelectQuery
de.dblab.page.HomePage ..> de.dblab.domain.Angestellte
de.dblab.page.HomePage ..> de.dblab.domain.Schaechte
de.dblab.page.HomePage ..> de.dblab.domain.Zeit
de.dblab.page.HomePage --|> de.dblab.page.TemplatePage
de.dblab.page.HomePage ..> java.util.Date
de.dblab.page.HomePage ..> java.util.List
de.dblab.page.HomePage ..> org.apache.cayenne.BaseContext
de.dblab.page.HomePage ..> org.apache.cayenne.CayenneDataObject
de.dblab.page.HomePage ..> org.apache.cayenne.ObjectContext
de.dblab.page.HomePage ..> org.apache.cayenne.configuration.server.ServerRuntime
de.dblab.page.HomePage ..> org.apache.cayenne.exp.Expression
de.dblab.page.HomePage ..> org.apache.cayenne.exp.ExpressionFactory
de.dblab.page.HomePage ..> org.apache.cayenne.query.SelectQuery
de.dblab.page.TemplatePage ..> java.lang.Override
de.dblab.page.TemplatePage --|> org.apache.click.Page
de.dblab.page.TemplatePage ..> org.apache.click.util.ClickUtils
de.dblab.page.angestellte.AngestellteEditPage ..> java.lang.Override
de.dblab.page.angestellte.AngestellteEditPage ..> org.apache.click.util.Bindable
de.dblab.page.angestellte.AngestellteEditPage ..> de.dblab.domain.Angestellte
de.dblab.page.angestellte.AngestellteEditPage ..> de.dblab.page.DataBaseService
de.dblab.page.angestellte.AngestellteEditPage ..> de.dblab.page.HomePage
de.dblab.page.angestellte.AngestellteEditPage --|> de.dblab.page.TemplatePage
de.dblab.page.angestellte.AngestellteEditPage ..> net.sf.click.extras.control.CalendarField
de.dblab.page.angestellte.AngestellteEditPage ..> org.apache.click.Page
de.dblab.page.angestellte.AngestellteEditPage ..> org.apache.click.control.Checkbox
de.dblab.page.angestellte.AngestellteEditPage ..> org.apache.click.control.FieldSet
de.dblab.page.angestellte.AngestellteEditPage ..> org.apache.click.control.Form
de.dblab.page.angestellte.AngestellteEditPage ..> org.apache.click.control.HiddenField
de.dblab.page.angestellte.AngestellteEditPage ..> org.apache.click.control.Submit
de.dblab.page.angestellte.AngestellteEditPage ..> org.apache.click.control.TextField
de.dblab.page.angestellte.AngestellteEditPage ..> org.apache.click.extras.control.IntegerField
de.dblab.page.angestellte.AngestellteNewForm ..> de.dblab.domain.Angestellte
de.dblab.page.angestellte.AngestellteNewForm ..> de.dblab.page.DataBaseService
de.dblab.page.angestellte.AngestellteNewForm ..> java.util.Date
de.dblab.page.angestellte.AngestellteNewForm ..> net.sf.click.extras.control.CalendarField
de.dblab.page.angestellte.AngestellteNewForm ..> org.apache.click.Control
de.dblab.page.angestellte.AngestellteNewForm ..> org.apache.click.control.FieldSet
de.dblab.page.angestellte.AngestellteNewForm --|> org.apache.click.control.Form
de.dblab.page.angestellte.AngestellteNewForm ..> org.apache.click.control.Submit
de.dblab.page.angestellte.AngestellteNewForm ..> org.apache.click.control.TextField
de.dblab.page.angestellte.AngestellteNewForm ..> org.apache.click.extras.control.IntegerField
de.dblab.page.angestellte.AngestellteNewForm --|> org.apache.click.ActionListener
de.dblab.page.angestellte.AngestelltePage ..> java.lang.Override
de.dblab.page.angestellte.AngestelltePage ..> de.dblab.domain.Angestellte
de.dblab.page.angestellte.AngestelltePage ..> de.dblab.page.DataBaseService
de.dblab.page.angestellte.AngestelltePage ..> de.dblab.page.HomePage
de.dblab.page.angestellte.AngestelltePage --|> de.dblab.page.TemplatePage
de.dblab.page.angestellte.AngestelltePage ..> java.text.ParseException
de.dblab.page.angestellte.AngestelltePage ..> java.text.SimpleDateFormat
de.dblab.page.angestellte.AngestelltePage ..> java.util.Calendar
de.dblab.page.angestellte.AngestelltePage ..> java.util.HashMap
de.dblab.page.angestellte.AngestelltePage ..> java.util.List
de.dblab.page.angestellte.AngestelltePage ..> org.apache.click.ActionResult
de.dblab.page.angestellte.AngestelltePage ..> org.apache.click.Control
de.dblab.page.angestellte.AngestelltePage ..> org.apache.click.ajax.DefaultAjaxBehavior
de.dblab.page.angestellte.AngestelltePage ..> org.apache.click.control.AbstractLink
de.dblab.page.angestellte.AngestelltePage ..> org.apache.click.control.Table
de.dblab.page.angestellte.AngestelltePage ..> org.apache.click.dataprovider.DataProvider
de.dblab.page.angestellte.AngestelltePage ..> org.apache.click.element.Element
de.dblab.page.angestellte.AngestelltePage ..> org.apache.click.element.JsImport
de.dblab.page.angestellte.AngestelltePage ..> org.apache.click.element.JsScript
de.dblab.page.angestellte.AngestelltePage ..> org.apache.click.extras.control.FieldColumn
de.dblab.page.angestellte.AngestelltePage ..> org.apache.click.extras.control.LinkDecorator
de.dblab.page.angestellte.AngestellteSearchForm ..> de.dblab.domain.Angestellte
de.dblab.page.angestellte.AngestellteSearchForm ..> net.sf.click.extras.control.CalendarField
de.dblab.page.angestellte.AngestellteSearchForm ..> org.apache.click.control.Field
de.dblab.page.angestellte.AngestellteSearchForm ..> org.apache.click.control.FieldSet
de.dblab.page.angestellte.AngestellteSearchForm --|> org.apache.click.control.Form
de.dblab.page.angestellte.AngestellteSearchForm ..> org.apache.click.control.Select
de.dblab.page.angestellte.AngestellteSearchForm ..> org.apache.click.control.Submit
de.dblab.page.angestellte.AngestellteSearchForm ..> org.apache.click.control.TextField
de.dblab.page.angestellte.AngestelterForm ..> java.lang.Override
de.dblab.page.angestellte.AngestelterForm ..> de.dblab.domain.Schaechte
de.dblab.page.angestellte.AngestelterForm ..> de.dblab.domain.Zeit
de.dblab.page.angestellte.AngestelterForm ..> de.dblab.page.DataBaseService
de.dblab.page.angestellte.AngestelterForm ..> de.dblab.page.HomePage
de.dblab.page.angestellte.AngestelterForm ..> de.dblab.page.angestellte.AngestelltePage
de.dblab.page.angestellte.AngestelterForm ..> java.util.List
de.dblab.page.angestellte.AngestelterForm ..> org.apache.click.ActionResult
de.dblab.page.angestellte.AngestelterForm ..> org.apache.click.Control
de.dblab.page.angestellte.AngestelterForm ..> org.apache.click.ajax.DefaultAjaxBehavior
de.dblab.page.angestellte.AngestelterForm ..> org.apache.click.control.AbstractLink
de.dblab.page.angestellte.AngestelterForm ..> org.apache.click.control.ActionLink
de.dblab.page.angestellte.AngestelterForm ..> org.apache.click.control.Button
de.dblab.page.angestellte.AngestelterForm ..> org.apache.click.control.Checkbox
de.dblab.page.angestellte.AngestelterForm ..> org.apache.click.control.Column
de.dblab.page.angestellte.AngestelterForm ..> org.apache.click.control.FieldSet
de.dblab.page.angestellte.AngestelterForm --|> org.apache.click.control.Form
de.dblab.page.angestellte.AngestelterForm ..> org.apache.click.control.Table
de.dblab.page.angestellte.AngestelterForm ..> org.apache.click.control.TextField
de.dblab.page.angestellte.AngestelterForm ..> org.apache.click.dataprovider.DataProvider
de.dblab.page.angestellte.AngestelterForm ..> org.apache.click.extras.control.DateField
de.dblab.page.angestellte.AngestelterForm ..> org.apache.click.extras.control.FieldColumn
de.dblab.page.angestellte.AngestelterForm ..> org.apache.click.extras.control.LinkDecorator
de.dblab.page.angestellte.AngestelterForm ..> org.apache.click.extras.control.TableInlinePaginator
de.dblab.page.angestellte.NewFormAngestellte ..> de.dblab.domain.Angestellte
de.dblab.page.angestellte.NewFormAngestellte ..> de.dblab.page.DataBaseService
de.dblab.page.angestellte.NewFormAngestellte ..> java.util.Date
de.dblab.page.angestellte.NewFormAngestellte ..> net.sf.click.extras.control.CalendarField
de.dblab.page.angestellte.NewFormAngestellte ..> org.apache.click.Control
de.dblab.page.angestellte.NewFormAngestellte ..> org.apache.click.control.FieldSet
de.dblab.page.angestellte.NewFormAngestellte --|> org.apache.click.control.Form
de.dblab.page.angestellte.NewFormAngestellte ..> org.apache.click.control.Submit
de.dblab.page.angestellte.NewFormAngestellte ..> org.apache.click.control.TextField
de.dblab.page.angestellte.NewFormAngestellte ..> org.apache.click.extras.control.IntegerField
de.dblab.page.angestellte.NewFormAngestellte --|> org.apache.click.ActionListener
de.dblab.page.schaechte.NewFormSchaechte ..> de.dblab.domain.Schaechte
de.dblab.page.schaechte.NewFormSchaechte ..> de.dblab.page.DataBaseService
de.dblab.page.schaechte.NewFormSchaechte ..> org.apache.click.Control
de.dblab.page.schaechte.NewFormSchaechte ..> org.apache.click.control.FieldSet
de.dblab.page.schaechte.NewFormSchaechte --|> org.apache.click.control.Form
de.dblab.page.schaechte.NewFormSchaechte ..> org.apache.click.control.Submit
de.dblab.page.schaechte.NewFormSchaechte ..> org.apache.click.control.TextField
de.dblab.page.schaechte.NewFormSchaechte ..> org.apache.click.extras.control.IntegerField
de.dblab.page.schaechte.NewFormSchaechte --|> org.apache.click.ActionListener
de.dblab.page.schaechte.SchaechteEditPage ..> java.lang.Override
de.dblab.page.schaechte.SchaechteEditPage ..> org.apache.click.util.Bindable
de.dblab.page.schaechte.SchaechteEditPage ..> de.dblab.domain.Schaechte
de.dblab.page.schaechte.SchaechteEditPage ..> de.dblab.page.DataBaseService
de.dblab.page.schaechte.SchaechteEditPage ..> de.dblab.page.HomePage
de.dblab.page.schaechte.SchaechteEditPage --|> de.dblab.page.TemplatePage
de.dblab.page.schaechte.SchaechteEditPage ..> org.apache.click.Page
de.dblab.page.schaechte.SchaechteEditPage ..> org.apache.click.control.Checkbox
de.dblab.page.schaechte.SchaechteEditPage ..> org.apache.click.control.FieldSet
de.dblab.page.schaechte.SchaechteEditPage ..> org.apache.click.control.Form
de.dblab.page.schaechte.SchaechteEditPage ..> org.apache.click.control.HiddenField
de.dblab.page.schaechte.SchaechteEditPage ..> org.apache.click.control.Select
de.dblab.page.schaechte.SchaechteEditPage ..> org.apache.click.control.Submit
de.dblab.page.schaechte.SchaechteEditPage ..> org.apache.click.control.TextField
de.dblab.page.schaechte.SchaechteForm ..> java.lang.Override
de.dblab.page.schaechte.SchaechteForm ..> de.dblab.domain.Angestellte
de.dblab.page.schaechte.SchaechteForm ..> de.dblab.domain.Schaechte
de.dblab.page.schaechte.SchaechteForm ..> de.dblab.domain.Zeit
de.dblab.page.schaechte.SchaechteForm ..> de.dblab.page.DataBaseService
de.dblab.page.schaechte.SchaechteForm ..> de.dblab.page.HomePage
de.dblab.page.schaechte.SchaechteForm ..> de.dblab.page.angestellte.AngestelltePage
de.dblab.page.schaechte.SchaechteForm ..> java.util.List
de.dblab.page.schaechte.SchaechteForm ..> org.apache.click.ActionResult
de.dblab.page.schaechte.SchaechteForm ..> org.apache.click.Control
de.dblab.page.schaechte.SchaechteForm ..> org.apache.click.ajax.DefaultAjaxBehavior
de.dblab.page.schaechte.SchaechteForm ..> org.apache.click.control.AbstractLink
de.dblab.page.schaechte.SchaechteForm ..> org.apache.click.control.ActionLink
de.dblab.page.schaechte.SchaechteForm ..> org.apache.click.control.Button
de.dblab.page.schaechte.SchaechteForm ..> org.apache.click.control.Checkbox
de.dblab.page.schaechte.SchaechteForm ..> org.apache.click.control.Column
de.dblab.page.schaechte.SchaechteForm ..> org.apache.click.control.FieldSet
de.dblab.page.schaechte.SchaechteForm --|> org.apache.click.control.Form
de.dblab.page.schaechte.SchaechteForm ..> org.apache.click.control.Table
de.dblab.page.schaechte.SchaechteForm ..> org.apache.click.control.TextField
de.dblab.page.schaechte.SchaechteForm ..> org.apache.click.dataprovider.DataProvider
de.dblab.page.schaechte.SchaechteForm ..> org.apache.click.extras.control.FieldColumn
de.dblab.page.schaechte.SchaechteForm ..> org.apache.click.extras.control.LinkDecorator
de.dblab.page.schaechte.SchaechteForm ..> org.apache.click.extras.control.TableInlinePaginator
de.dblab.page.schaechte.SchaechteNewForm ..> de.dblab.domain.Angestellte
de.dblab.page.schaechte.SchaechteNewForm ..> de.dblab.domain.Schaechte
de.dblab.page.schaechte.SchaechteNewForm ..> de.dblab.page.DataBaseService
de.dblab.page.schaechte.SchaechteNewForm ..> de.dblab.page.schaechte.SchaechtePage
de.dblab.page.schaechte.SchaechteNewForm ..> java.util.List
de.dblab.page.schaechte.SchaechteNewForm ..> org.apache.click.Control
de.dblab.page.schaechte.SchaechteNewForm ..> org.apache.click.control.FieldSet
de.dblab.page.schaechte.SchaechteNewForm --|> org.apache.click.control.Form
de.dblab.page.schaechte.SchaechteNewForm ..> org.apache.click.control.Select
de.dblab.page.schaechte.SchaechteNewForm ..> org.apache.click.control.Submit
de.dblab.page.schaechte.SchaechteNewForm ..> org.apache.click.control.TextField
de.dblab.page.schaechte.SchaechteNewForm ..> org.apache.click.dataprovider.DataProvider
de.dblab.page.schaechte.SchaechteNewForm ..> org.apache.click.extras.control.IntegerField
de.dblab.page.schaechte.SchaechteNewForm --|> org.apache.click.ActionListener
de.dblab.page.schaechte.SchaechtePage ..> java.lang.Override
de.dblab.page.schaechte.SchaechtePage ..> de.dblab.domain.Schaechte
de.dblab.page.schaechte.SchaechtePage ..> de.dblab.page.DataBaseService
de.dblab.page.schaechte.SchaechtePage ..> de.dblab.page.HomePage
de.dblab.page.schaechte.SchaechtePage --|> de.dblab.page.TemplatePage
de.dblab.page.schaechte.SchaechtePage ..> java.util.HashMap
de.dblab.page.schaechte.SchaechtePage ..> java.util.List
de.dblab.page.schaechte.SchaechtePage ..> org.apache.click.ActionResult
de.dblab.page.schaechte.SchaechtePage ..> org.apache.click.Control
de.dblab.page.schaechte.SchaechtePage ..> org.apache.click.ajax.DefaultAjaxBehavior
de.dblab.page.schaechte.SchaechtePage ..> org.apache.click.control.AbstractLink
de.dblab.page.schaechte.SchaechtePage ..> org.apache.click.control.ActionLink
de.dblab.page.schaechte.SchaechtePage ..> org.apache.click.control.Checkbox
de.dblab.page.schaechte.SchaechtePage ..> org.apache.click.control.Column
de.dblab.page.schaechte.SchaechtePage ..> org.apache.click.control.PageLink
de.dblab.page.schaechte.SchaechtePage ..> org.apache.click.control.Table
de.dblab.page.schaechte.SchaechtePage ..> org.apache.click.dataprovider.DataProvider
de.dblab.page.schaechte.SchaechtePage ..> org.apache.click.element.Element
de.dblab.page.schaechte.SchaechtePage ..> org.apache.click.element.JsImport
de.dblab.page.schaechte.SchaechtePage ..> org.apache.click.element.JsScript
de.dblab.page.schaechte.SchaechtePage ..> org.apache.click.extras.control.FieldColumn
de.dblab.page.schaechte.SchaechtePage ..> org.apache.click.extras.control.LinkDecorator
de.dblab.page.schaechte.SchaechteSearchForm ..> de.dblab.domain.Schaechte
de.dblab.page.schaechte.SchaechteSearchForm ..> org.apache.click.control.FieldSet
de.dblab.page.schaechte.SchaechteSearchForm --|> org.apache.click.control.Form
de.dblab.page.schaechte.SchaechteSearchForm ..> org.apache.click.control.Select
de.dblab.page.schaechte.SchaechteSearchForm ..> org.apache.click.control.Submit
de.dblab.page.schaechte.SchaechteSearchForm ..> org.apache.click.control.TextField
de.dblab.service.cayenne.Property ..> org.apache.cayenne.exp.Expression
de.dblab.service.cayenne.Property ..> org.apache.cayenne.exp.ExpressionFactory
de.dblab.service.cayenne.Property --|> org.apache.cayenne.exp.Property
@enduml

@enduml