package de.dblab.domain.auto;

import java.util.Date;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import de.dblab.domain.Schaechte;
import de.dblab.domain.Zeit;

/**
 * Class _Angestellte was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Angestellte extends CayenneDataObject {

    public static final String ID_PK_COLUMN = "id";

    public static final Property<Boolean> ENTLASSENE = new Property<Boolean>("entlassene");
    public static final Property<Date> GEBURTSDATUM = new Property<Date>("geburtsdatum");
    public static final Property<Integer> GEHALT = new Property<Integer>("gehalt");
    public static final Property<Integer> ID = new Property<Integer>("id");
    public static final Property<String> NACHNAME = new Property<String>("nachname");
    public static final Property<String> NAME = new Property<String>("name");
    public static final Property<String> STELLE = new Property<String>("stelle");
    public static final Property<List<Schaechte>> SCHAECHTE_ARRAY = new Property<List<Schaechte>>("schaechteArray");
    public static final Property<List<Schaechte>> schaechteZulassung = new Property<List<Schaechte>>("schaechteArray1");
    public static final Property<List<Zeit>> ZEIT_ARRAY = new Property<List<Zeit>>("zeitArray");

    public void setEntlassene(Boolean entlassene) {
        writeProperty("entlassene", entlassene);
    }
    public Boolean getEntlassene() {
        return (Boolean)readProperty("entlassene");
    }

    public void setGeburtsdatum(Date geburtsdatum) {
        writeProperty("geburtsdatum", geburtsdatum);
    }
    public Date getGeburtsdatum() {
        return (Date)readProperty("geburtsdatum");
    }

    public void setGehalt(Integer gehalt) {
        writeProperty("gehalt", gehalt);
    }
    public Integer getGehalt() {
        return (Integer)readProperty("gehalt");
    }

    public void setId(Integer id) {
        writeProperty("id", id);
    }
    public Integer getId() {
        return (Integer)readProperty("id");
    }

    public void setNachname(String nachname) {
        writeProperty("nachname", nachname);
    }
    public String getNachname() {
        return (String)readProperty("nachname");
    }

    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }

    public void setStelle(String stelle) {
        writeProperty("stelle", stelle);
    }
    public String getStelle() {
        return (String)readProperty("stelle");
    }

    public void addToSchaechteArray(Schaechte obj) {
        addToManyTarget("schaechteArray", obj, true);
    }
    public void removeFromSchaechteArray(Schaechte obj) {
        removeToManyTarget("schaechteArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Schaechte> getSchaechteArray() {
        return (List<Schaechte>)readProperty("schaechteArray");
    }


    public void addToSchaechteArray1(Schaechte obj) {
        addToManyTarget("schaechteArray1", obj, true);
    }
    public void removeFromSchaechteArray1(Schaechte obj) {
        removeToManyTarget("schaechteArray1", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Schaechte> getSchaechteArray1() {
        return (List<Schaechte>)readProperty("schaechteArray1");
    }


    public void addToZeitArray(Zeit obj) {
        addToManyTarget("zeitArray", obj, true);
    }
    public void removeFromZeitArray(Zeit obj) {
        removeToManyTarget("zeitArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Zeit> getZeitArray() {
        return (List<Zeit>)readProperty("zeitArray");
    }


}
